# Copyright 2021 Adam Chalkley
#
# https://github.com/atc0005/send2teams
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

######################################################################
# Monitor Go module dependency updates
######################################################################

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Go Dependency"

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "development"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Go Dependency"

  ######################################################################
  # Monitor GitHub Actions dependency updates
  ######################################################################

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "CI Dependency"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "development"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "CI Dependency"

  ######################################################################
  # Monitor Go updates to service as a reminder to generate new releases
  ######################################################################

  - package-ecosystem: docker
    directory: "/dependabot/docker/go"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
      - "todo/release"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Go Runtime"
    ignore:
      - dependency-name: "golang"
        versions:
          - ">= 1.22"
          - "< 1.21"

  - package-ecosystem: docker
    directory: "/dependabot/docker/go"
    open-pull-requests-limit: 10
    target-branch: "development"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
      - "todo/release"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Go Runtime"

  ######################################################################
  # Monitor images used to build project releases
  ######################################################################

  - package-ecosystem: docker
    directory: "/dependabot/docker/builds"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "builds"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Build Image"

  - package-ecosystem: docker
    directory: "/dependabot/docker/builds"
    open-pull-requests-limit: 10
    target-branch: "development"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "builds"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Build Image"
