# Copyright 2021 Adam Chalkley
#
# https://github.com/atc0005/send2teams
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

issues:
  # equivalent CLI flag: --exclude-use-default
  #
  # see:
  #   atc0005/todo#29
  #   golangci-lint/golangci-lint#1249
  #   golangci-lint/golangci-lint#413
  exclude-use-default: false

linters:
  enable:
    # https://github.com/atc0005/go-ci/issues/1024
    # - depguard
    - dogsled
    - dupl
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - prealloc
    - revive
    - stylecheck
    - unconvert

  disable:
    - maligned

linters-settings:
  govet:
    enable:
      - fieldalignment
