# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/send2teams
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

linters:
  enable:
    - dogsled
    - goimports
    - gosec
    - stylecheck
    - goconst
    - depguard
    - prealloc
    - misspell
    - maligned
    - dupl
    - unconvert
    - gofmt
    - golint
    - gocritic
    - scopelint
