# Copyright 2023 Adam Chalkley
#
# https://github.com/atc0005/send2teams
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.


# Purpose:
#
# Dependabot-maintained Dockerfile used by Makefile-driven release builds.
#

# https://github.com/atc0005/go-ci/releases
# https://github.com/atc0005/go-ci/pkgs/container/go-ci
FROM ghcr.io/atc0005/go-ci:go-ci-oldstable-build-v0.9.2
