# Copyright 2021 Adam Chalkley
#
# https://github.com/atc0005/send2teams
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.


# Purpose:
#
# "Canary" Dockerfile for Go updates, monitored by Dependabot.
#
# After Dependabot provides a (valid) Pull Request to update this file, I
# should begin the process of preparing a new project release (including
# binaries) to reflect that version of Go.

# https://hub.docker.com/_/golang
FROM golang:1.19.3
