# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/send2teams
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Lint and Build using Makefile

# Run builds for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  #push:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_code_with_makefile:
    name: Lint codebase using Makefile
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 10
    container:
      image: "index.docker.io/golang:latest"

    steps:
      - name: Print go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.2

      # bsdmainutils provides "column" which is used by the Makefile
      - name: Install Ubuntu packages
        run: apt-get update && apt-get install -y --no-install-recommends make gcc bsdmainutils

      - name: Install Go linting tools
        run: make lintinstall

      # NOTE: We are intentionally *not* removing the repo-provided config
      # file (per GH-281) as this workflow is intended to emulate running the
      # Makefile via a local dev environment.
      #
      # - name: Remove repo-provided golangci-lint config file
      #   run: |
      #     # Remove the copy of the config file bundled with the repo/code so
      #     # that the configuration provided by the atc0005/go-ci project is
      #     # used instead
      #     rm -vf .golangci.yml

      - name: Run Go linting tools using project Makefile
        run: make linting

  build_code_with_makefile:
    name: Build codebase using Makefile
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 10
    container:
      image: "index.docker.io/golang:latest"

    steps:
      - name: Print go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.2

      # bsdmainutils provides "column" which is used by the Makefile
      - name: Install Ubuntu packages
        run: apt-get update && apt-get install -y --no-install-recommends make gcc bsdmainutils

      - name: Build using project Makefile
        run: make all
