#!/bin/bash

# Copyright 2019 Adam Chalkley
#
# https://github.com/atc0005/send2teams
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Validate Docs

# Run Workflow for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_markdown:
    name: Lint Markdown files
    runs-on: "ubuntu-latest"
    # Default: 360 minutes
    timeout-minutes: 10

    steps:
      - name: Setup Node
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Markdown linting tools
        run: |
          npm install markdownlint --save-dev
          npm install -g markdownlint-cli

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Markdown linting tools
        run: |
          # The `.markdownlint.yml` file specifies config settings for this
          # linter, including which linting rules to ignore.
          markdownlint '**/*.md' --ignore node_modules
