# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/send2teams
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Project Analysis

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

    # `synchronized` seems to equate to pushing new commits to a linked branch
    # (whether force-pushed or not)
    types: [opened, synchronize]
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    # │ │ │ │ │
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * *
    - cron: "19 2 * * 0"

jobs:
  lint:
    name: Lint
    uses: atc0005/shared-project-resources/.github/workflows/lint-project-files.yml@master

  vulnerability:
    name: Vulnerability
    uses: atc0005/shared-project-resources/.github/workflows/vulnerability-analysis.yml@master

  go_mod_validation:
    name: Go Module Validation
    uses: atc0005/shared-project-resources/.github/workflows/go-mod-validation.yml@master

  dependency_updates:
    name: Dependency Updates
    uses: atc0005/shared-project-resources/.github/workflows/dependency-updates.yml@master
