# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/send2teams
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Project Analysis

on:
  push:
  # branches: [master]

  pull_request:
    # `synchronized` seems to equate to pushing new commits to a linked branch
    # (whether force-pushed or not)
    types: [opened, synchronize]

    # The branches below must be a subset of the branches above
    # branches: [master]

jobs:
  lint:
    # Only run this job on non-push events (e.g., pull requests)
    if: github.event_name != 'push'
    name: Lint
    uses: atc0005/shared-project-resources/.github/workflows/lint-project-files.yml@master

  vulnerability:
    name: Vulnerability
    uses: atc0005/shared-project-resources/.github/workflows/vulnerability-analysis.yml@master

  go_mod_validation:
    # Only run this job on non-push events (e.g., pull requests)
    if: github.event_name != 'push'
    name: Go Module Validation
    uses: atc0005/shared-project-resources/.github/workflows/go-mod-validation.yml@master

  dependency_updates:
    # Only run this job on non-push events (e.g., pull requests)
    if: github.event_name != 'push'
    name: Dependency Updates
    uses: atc0005/shared-project-resources/.github/workflows/dependency-updates.yml@master
