# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/send2teams
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Push Validation

# Run jobs when someone pushes to a repository branch. This workflow is
# intended to provide quick validation of content changes for Pull Requests
# (new, updated).
on:
  push:

jobs:
  quick_validation:
    name: Quick
    uses: atc0005/shared-project-resources/.github/workflows/quick-validation.yml@master
