# See LICENSE file in this repo for license details.

name: Release Build

on:
  push:
    tags:
      # Match any semver tag, rely on the imported workflow to apply necessary
      # logic to separate "stable" release builds from "prerelease" builds.
      - "v[0-9]+.[0-9]+.*"

jobs:
  release_build:
    name: Generate release build

    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    permissions:
      contents: write
      discussions: write

    uses: atc0005/shared-project-resources/.github/workflows/release-build.yml@master
