# See LICENSE file in this repo for license details.

name: Scheduled Monthly

on:
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    # │ │ │ │ │
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * *
    - cron: "30 4 1 * *"

jobs:
  lint:
    name: Monthly Tasks
    uses: atc0005/shared-project-resources/.github/workflows/scheduled-monthly.yml@master
